
server:
  port: 8081
  servlet:
    context-path: /api

spring:
#  ?? ? ??? ?? ???? ?? => local
  profiles:
    active: local
    include: key
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
---
# local ???? ?? ?
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${my-db.url}
    username: ${my-db.username}
    password: ${my-db.password}
    driver-class-name: ${my-db.driver-class-name}

---
# server ???? ???
spring:
  config:
    activate:
      on-profile: server
  datasource:
    url: ENC()
    username: ENC()
    password: ENC()
    driver-class-name: com.mysql.cj.jdbc.Driver

