server:
  port: 8081
  servlet:
    context-path: /api

spring:
#  ?? ? ??? ?? ???? ?? => local
  profiles:
    active: local
    include: key
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: -1
      max-request-size : -1

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

openai:
  api:
    key: ENC(/SrX6Kd5v3lr+0NOTKzm8gbQ4IWEVTYKsN5tmyo3gCVUzFNKJmpWq/XzSqF2+gtKryYlR5PbUERirkjSWuVag1MU7BG7eh1j)

---
# local ???? ?? ?
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${my-db.url}
    username: ${my-db.username}
    password: ${my-db.password}
    driver-class-name: ${my-db.driver-class-name}

---
# server ???? ???
spring:
  config:
    activate:
      on-profile: server
  datasource:
    url: ENC()
    username: ENC()
    password: ENC()
    driver-class-name: com.mysql.cj.jdbc.Driver



