server:
  port: 5000
  servlet:
    context-path: /api

spring:
#  ?? ? ??? ?? ???? ?? => local
  profiles:
    active: server
    include: key
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: -1
      max-request-size : -1
  data:
    redis:
      host: ENC(bpvQWREaT+PKGlhOg/jv8cYQcmwENp5zvN+2MUe47mM=)
      port: ENC(Khu6v//bNi7/6cl0mr519g==)
      username:
      password: ENC(Q9ZQLmy0sa/53pyJLsNJrfJpWKwDHll7)

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

openai:
  api:
    key: ENC(/SrX6Kd5v3lr+0NOTKzm8gbQ4IWEVTYKsN5tmyo3gCVUzFNKJmpWq/XzSqF2+gtKryYlR5PbUERirkjSWuVag1MU7BG7eh1j)

#S3 key
cloud :
  aws :
    credentials :
      accessKey : ENC(DMrxWMB7HK4CUX05ct2a3ltIEyE6WXCWbM6PjsAUsRc=)
      secretKey : ENC(JvFCxy8PXNGV3ClIf7e6sykNnaC7tcYSPJ5jnvInVsxwEYGuo9sO5mqCJ2Av+fyNqnxXo62uk0w=)

    #S3 bucketName
    s3 :
      bucketName : ENC(6nlRvB9W3Q1YoHb3cnk/1Q==)
    #S3 location
    region :
      static : ENC(E5aWo1K77RUoLWpsi4kxGUxAd4mKBDI5)
    #cloud formation ??? ???? ?? ??.
    stack :
      auto : false

---
# local ???? ?? ?
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${my-db.url}
    username: ${my-db.username}
    password: ${my-db.password}
    driver-class-name: ${my-db.driver-class-name}
  data:
    mongodb:
      database: ${my-mongodb.database}
      host: ${my-mongodb.host}
      port: ${my-mongodb.port}

---
# server ???? ???
spring:
  config:
    activate:
      on-profile: server
  datasource:
    url: ENC(YTNP9PqQyUHZ3g97qdDPuZTZkwTtBNap96lvGv99XEVnaz5Kh0qEjKnEe92uAaUaWf+ZkTvckpDH0/VGPzjKb2LlCRhECGMdXoXE2Crx8gWvc45wyaqvQg==)
    username: ENC(Nd9hps8Hr207vp8fZgjt+w==)
    password: ENC(MteBDlIIwXGZRw7gjOVX97iyvl1oLNru)
    driver-class-name: com.mysql.cj.jdbc.Driver

    mongodb:
      uri: ENC(Bf33id/NT451ymS94xr23Mp5TlZShmuy5ZUIbPwoMMUMIPAg124BRIetV//M+JsYauF4DT7mZ1bsjJtb1sWsifi42+jcs/lidtGhNvE/R2RqGwHioOtZ2A==)



