my-db:
  url: jdbc:mysql://localhost:3306/ukkikki?useSSL=false&serverTimezone=UTC
  username: root
  password: 'ssafy'
  driver-class-name: com.mysql.cj.jdbc.Driver

# jasypt key
encryptor:
  key: 'I*EsAlz4Hwjnhd+jP6doEu-IgOM!+8'