server:
  port: 5000
  servlet:
    context-path: /api

spring:
#  ?? ? ??? ?? ???? ?? => local
  profiles:
    active: server
    include: key
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: -1
      max-request-size : -1
  data:
    redis:
      host: ENC(bpvQWREaT+PKGlhOg/jv8cYQcmwENp5zvN+2MUe47mM=)
      port: ENC(Khu6v//bNi7/6cl0mr519g==)
      username:
      password: ENC(Q9ZQLmy0sa/53pyJLsNJrfJpWKwDHll7)

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

openai:
  api:
    key: ENC(/SrX6Kd5v3lr+0NOTKzm8gbQ4IWEVTYKsN5tmyo3gCVUzFNKJmpWq/XzSqF2+gtKryYlR5PbUERirkjSWuVag1MU7BG7eh1j)

#S3 key
cloud :
  aws :
    credentials :
      accessKey : ENC(DMrxWMB7HK4CUX05ct2a3ltIEyE6WXCWbM6PjsAUsRc=)
      secretKey : ENC(JvFCxy8PXNGV3ClIf7e6sykNnaC7tcYSPJ5jnvInVsxwEYGuo9sO5mqCJ2Av+fyNqnxXo62uk0w=)

    #S3 bucketName
    s3 :
      bucketName : ENC(6nlRvB9W3Q1YoHb3cnk/1Q==)
    #S3 location
    region :
      static : ENC(E5aWo1K77RUoLWpsi4kxGUxAd4mKBDI5)
    #cloud formation ??? ???? ?? ??.
    stack :
      auto : false

---
# local ???? ?? ?
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${my-db.url}
    username: ${my-db.username}
    password: ${my-db.password}
    driver-class-name: ${my-db.driver-class-name}
  data:
    mongodb:
      database: ${my-mongodb.database}
      host: ${my-mongodb.host}
      port: ${my-mongodb.port}
---
# server ???? ???
spring:
  config:
    activate:
      on-profile: server
  datasource:
    url: ENC(YTNP9PqQyUHZ3g97qdDPuZTZkwTtBNap96lvGv99XEVnaz5Kh0qEjKnEe92uAaUaWf+ZkTvckpDH0/VGPzjKb2LlCRhECGMdXoXE2Crx8gWvc45wyaqvQg==)
    username: ENC(Nd9hps8Hr207vp8fZgjt+w==)
    password: ENC(MteBDlIIwXGZRw7gjOVX97iyvl1oLNru)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: ENC(Dn8jMMud9FSpbiIaHLjDNIIuH/EWmMgLVYBwAVmlNwtLU7md4SSguF95a3k7bHLSXVsmmlOVfTMT1/eNHjPTffwZ+N8ipjJMgu2l7MiA11y4QNqxBFjkrw==)

---
# kakao
spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ENC(9EljJ7oPUEA9u2V9DnA+JQy2PbbUfmHJYaAiOHh85lZYkkQrjoxSBgV0fNFcsrH9)
            client-secret: ENC(qziOW7UxQ07u+b17onp9vMpIG0wFljbDb/j1mAUoBHMfFdhbezWJ8lLAO3q4Fxn4)
            client-authentication-method: client_secret_post
#            redirect-uri: http://localhost:5000/api/login/oauth2/code/kakao
            redirect-uri: https://k10d202.p.ssafy.io/api/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
---
jwt:
  key : ENC(NB4AWZl6GSCm7rW6gXERJpDE7NyU7UwTmVZkS2P+Ujc0NWagOtaJQQrB+/lbqTlDT045BL+2JT4=)

webClient:
  baseUrl: ENC(Rsq3wm9AsUNAQNthqARdC8TS5XuPJCn4cjVbIDHq0Yp2Lxv7a5aH6eqbKlcC9fTa)